version: '3'
services:
  django:
    build:
      context: .
      dockerfile: ./compose/DockerFile
    ports:
      - 8000:8000
    volumes:
      - ./codeium:/app
    depends_on:
      - db
    environment:
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: hellonepal
      DATABASE_HOST: db
      DATABASE_PORT: 5432
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_NAME: postgres
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: hellonepal
      POSTGRES_PORT: 5432
    ports:
      - 5434:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
